name: CI-CD-Pipeline-to-deploy-angularapp-to-awsS3
env:
  AMPLIFY_PACKAGE_S3_BUCKET_NAME: "angular-testing-s3"
  #AWS_REGION: "us-east-1"
  APP_ID: "app6866" 
  PACKAGE_NAME: "hello-world"

on: 
  push:
    branches:
    - master

permissions:
      packages: write
      contents: read
      id-token: write

jobs:
  deploy:
  ci-pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
    
    - name: Build
      run: npm run build
    
    - name: Create Zip Deployment Package
      run: cd dist/$PACKAGE_NAME && zip -r $PACKAGE_NAME * -x *.git*

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        #audience: sts.amazonaws.com
        role-to-assume: arn:aws:iam::497896953208:role/dev_role_s3activity
        #aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        #aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Copy Deployment Package to AWS S3
      run: |
        cd dist/$PACKAGE_NAME && \
        aws s3 cp $PACKAGE_NAME.zip s3://$AMPLIFY_PACKAGE_S3_BUCKET_NAME

    cd-pipeline:
      runs-on: ubuntu-latest
      needs: [ci-pipeline]
    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
        #audience: sts.amazonaws.com
        role-to-assume: arn:aws:iam::497896953208:role/dev_role_s3activity
        aws-region: us-east-1
     
      - name: Deploy the new application version
        run: |
          aws amplify start-deployment \
            --app-id $APP_ID \
            --branch-name manual \
            --source-url s3://$AMPLIFY_PACKAGE_S3_BUCKET_NAME/$PACKAGE_NAME.zip


